version: '3'

services:
  express:
    build: .
    container_name: vcards_app
    volumes:
      - ./source/:/usr/src/app/source/
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env
  
  db:
    image: mongo
    container_name: vcards_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}